### ISSUE TITLE
HO3D_v2 challenge in codalab is down

### ISSUE THREAD

**Issue by hxwork** [shreyashampali/HOnnotate#37]
Hi,

The submission status is "Failed". Could you please help us fix this problem? Thanks in advance.
Here is the screenshot.
<img width="1304" alt="image" src="https://github.com/shreyashampali/HOnnotate/assets/46584121/e57443f4-bcc5-494d-bd43-264a58ea0c95">

**Comment by hxwork** [comment]
Hi,

According to [this issue](https://github.com/codalab/codalab-competitions/issues/3485#issuecomment-2107481094), it seems only the organizer can solve this problem. Looking forward to your reply.

**Comment by shreyashampali** [comment]
Hi, I fixed this issue on Sunday. Are you still facing the issue?

**Comment by hxwork** [comment]
> Hi, I fixed this issue on Sunday. Are you still facing the issue?

Thanks for your help. It works now.

**Comment by zhangy76** [comment]
Dear author,

Thank you for the quick response. The same issue also appears to HO3D_v3 challenge. After the fixing, it becomes: 

`
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Execution time limit exceeded!
`

Could you please to kindly provide some help? Thanks!

**Comment by shreyashampali** [comment]
hi, it should be working fine now. Sorry for the trouble here!

**Comment by zhangy76** [comment]
thanks! the servers work good now.
