### ISSUE TITLE
Decision is pending.

### ISSUE THREAD

**Issue by zhoujun-7** [shreyashampali/HOnnotate#39]
I am interested in participating in the [HO3D_2 challenge](https://codalab.lisn.upsaclay.fr/competitions/4318#participate). Codalab shows the following information:

`Your request to participate in this challenge has been received and a decision is pending.`

Could you please let me know how long it typically takes for the administrator to respond?

Thank you.

**Comment by liangshenglei** [comment]
May I ask if you have resolved this issue? If you could provide assistance, thank you very much

**Comment by liangshenglei** [comment]
II also want to know how long you've been waiting. Thanks

**Comment by zhoujun-7** [comment]
> II also want to know how long you've been waiting. Thanks

Yes, less than 6 hours.
