### ISSUE TITLE
about the joint order

### ISSUE THREAD

**Issue by MengHao666** [shreyashampali/HOnnotate#4]
First,thank u for such great work!
Now I have been confused about the joint order in the dataset.
In the ho3d_v2 dataset, you mention the joint order is different from that of MANO model.
And now I take part in the competetion [Ho3d_v2 Codalab competition](https://competitions.codalab.org/competitions/22485#learn_the_details) u provide, and I get the reults which have high error in joint loacation but much lower mesh error.
So I wonder if the joint order in the evaluation dataset is also different from that of original MANO model?
Hope you could provide some suggestion,thank u!

**Comment by shreyashampali** [comment]
hi,
The joint orderings follow the MANO model ordering even for the evaluation set as mentioned [here](https://competitions.codalab.org/competitions/22485#learn_the_details-evaluation). Could you please point me to the place where it is mentioned that the joint order is different from MANO model?

**Comment by MengHao666** [comment]
Thanks for the quick reply.
I'm sorry to confuse the code of [jointsMapManoToSimple](https://github.com/shreyashampali/ho3d/blob/master/vis_HO3D.py#L41)  u provided and that of [hassony's self.reorder_idxs](https://github.com/hassony2/handobjectconsist/blob/3f32ce0f9a239052bc9cb4e3d78582559cd4e757/meshreg/datasets/ho3dv2.py#L54).They may change the oreder to adapt to the differentiable Mano layer they proposed.

In my own understanding , u use jointsMapManoToSimple only for simple visualization ? Is that true?

Thanks u again!

**Comment by MengHao666** [comment]
Another question is that whether the order of samples in train.txt has been carefully shuffled to ensure uniform distribution.
Hope to get your suggestions, thanks!

**Comment by shreyashampali** [comment]
yes, jointsMapManoToSimple is only for visualization.
The samples in train.txt are just randomly shuffled. It does not guarantee uniform distribution

**Comment by MengHao666** [comment]
Ok,thanks a lot!
