### ISSUE TITLE
About pose constraints

### ISSUE THREAD

**Issue by MengHao666** [shreyashampali/HOnnotate#5]
Hi，Hampali.
Thanks for this great work!

I have some confusions about pose constraints:
  1. It is said in paper that u use E<sub>joint</sub> to restrict joint angles in the optimization process and baseline method.And then u give the upper and lower limits for every 45 joint angle parameters in Supplementary Material. 
But in [constraints.py](https://github.com/shreyashampali/HOnnotate/blob/master/optimization/ghope/constraints.py), u use [ self.validThetaIDs](https://github.com/shreyashampali/ho3d/blob/master/vis_HO3D.py#L25) to limit 33 of joint angle params. only.And I have checked that other 15 params are all zero in the whole train set.
So why don't u only optimze 33 pose params and set 15 other params. to 0 in optimization process and baseline method?

2.As u said in the paper , L2 regularizer function is a more common method to limit joint angles. Have u compared the different effects of L2 regularizer function without PCA and your method proposed as equation 8 in paper?

Hope for your kind reply.

All best
Hao Meng

**Comment by shreyashampali** [comment]
hi Hao Meng,
1. In the code only 33 parameters specified in the validThetaIDs are optimized. Those that are not optimized are set to zero. The limits of thetaIDs which are not optimized are set to (0.0,0.0) in the supplementary material
2. Not sure if I understood the question. Could you please explain what you mean by 'L2 regularizer function without PCA'? We did not do a quantitative study of the effect of using L2 regularizer vs using joint angle constraint term.

**Comment by MengHao666** [comment]
Hi,

Thanks for the clear response and sorry for late reply.
By 'L2 regularizer function without PCA', I mean i try to caculate MSEloss between full 48 pose params.(3 for global rotation and 45 for other joint rotations) and zeros vector  with same size.
I just found in my previous  experiment ，such 'L2 regularizer function without PCA'  have better outcome than the pose constriants in your paper. By the way, could  the constraints of 33 joint angles (15 other joint angles could only be 0)in your paper  fit other datasets? How could u give such quantitative representation?

Really thanks for the generous reply. I do pay efforts in studying this wonderful dataset.
All the best!

**Comment by shreyashampali** [comment]
hi,
That's interesting to know that  'L2 regularizer function without PCA'  works better.
We tried to tune the joint angles constraints based on our grasp poses in the datasets. It is possible that these joint limits are not accurate enough for some poses achieved by other hand-only datasets.

**Comment by MengHao666** [comment]
Thanks a lot for the clear reply.
Another question, do the poses in the evaluation set also obey the pose constraint limits proposed in paper?

All best.
Hao Meng

**Comment by shreyashampali** [comment]
yes, they follow the same pose constraints limits...
