### ISSUE TITLE
submission error in codalab

### ISSUE THREAD

**Issue by zly9844** [shreyashampali/HOnnotate#7]
Hi,
   First thanks for such great work!
   When I submit my result in codalab , I meet errors as follows:
          `WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/tmp/codalab/tmp3wJDBP/run/program/evaluate.py", line 400, in <module>
    set_name='evaluation'
  File "/tmp/codalab/tmp3wJDBP/run/program/evaluate.py", line 214, in main
    pred_file = _search_pred_file(pred_path, pred_file_name)
  File "/tmp/codalab/tmp3wJDBP/run/program/evaluate.py", line 200, in _search_pred_file
    raise Exception('Giving up, because its not clear which file to evaluate.')
Exception: Giving up, because its not clear which file to evaluate.`

Could you spare some time to solve it?
Thanks a lot!

**Comment by shreyashampali** [comment]
Hi,
Your zip file must contain only 1 json file with the results. You currently have a have folder named 'json' inside the zip which in turn contains the json file.
Please refer to https://github.com/shreyashampali/ho3d/blob/master/eval.py for the evaluation script.

**Comment by zly9844** [comment]
Thank you for reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shreyashampali/HOnnotate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 晚上8:51
收件人:&nbsp;"shreyashampali/HOnnotate"<HOnnotate@noreply.github.com&gt;;
抄送:&nbsp;"LandMoon"<508366164@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shreyashampali/HOnnotate] submission error in codalab (#7)





 
Hi,
 Your zip file must contain only 1 json file with the results. You currently have a have folder named 'json' inside the zip which in turn contains the json file.
 Please refer to https://github.com/shreyashampali/ho3d/blob/master/eval.py for the evaluation script.
